### ISSUE TITLE
Correlator meas breaks for C20

### ISSUE THREAD

**Issue by jl-wynen** [jl-wynen/isle#11]
The single particle correlator measurement does not work for C20. Running it with Nt=16 gives
```
Traceback (most recent call last):
  File "docs/examples/measure.py", line 72, in <module>
    main()
  File "docs/examples/measure.py", line 69, in main
    measState(measurements, configRange=args.configs)
  File "/home/jl/Uni/PhD/cns/isle/src/isle/drivers/meas.py", line 29, in __call__
    self.mapOverConfigs(measurements, configRange)
  File "/home/jl/Uni/PhD/cns/isle/src/isle/drivers/meas.py", line 55, in mapOverConfigs
    measurement(phi, action, i)
  File "/home/jl/Uni/PhD/cns/isle/src/isle/meas/singleParticleCorrelator.py", line 42, in __call__
    propagators = res.reshape([len(self.irreps), nt, nt, len(self.irreps)])
ValueError: cannot reshape array of size 81920 into shape (16,16,16,16)
```

Don't know whether this is an old bug and no one noticed or whether it was introduced in 7bf5ad399edff266948aa84ca5b7a6f085103940.
I couln't reproduce this with any other lattice.

**Comment by evanberkowitz** [comment]
Hmmmm OK I'll investigate.

**Comment by evanberkowitz** [comment]
This must have been introduced in 7bf5ad3, because I have, in the past, calculated correlators for C20!  I believe the problem is that scipy's [`la.orth`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.orth.html) produces an orthonormal basis for the *range* of the input matrix, via SVD.

C20 has 4 zero eigenvalues so the range is 16 vectors rather than 20, and `81920 = 16*16*16*20 ( = nt^2 * la.orth )`.

I'm on it.

**Comment by jl-wynen** [comment]
I think this is fixed since the split correlator <-> propagator measurements.
@evanberkowitz Can you confirm?

**Comment by evanberkowitz** [comment]
Yes, this is fixed.  I just ran a c20 lattice with beta=3, U=2, µ=0, sigmaKappa = -1, diagonal, in the particle-hole basis.  Generated ~ 1000 configurations, measured, no problem.

Something that is missing is the analysis step where the correlator is diagonalized.  There was code that did this---I don't know where it went!  It's only critical for further diagonalizing when there are multiple copies of a single irrep that can mix.
