### ISSUE TITLE
Do not hold measurements for all configurations in memory

### ISSUE THREAD

**Issue by jl-wynen** [jl-wynen/isle#18]
For large lattices, not all measurement results can be kept in RAM at the same time. Especially correlators run out of memory quickly and crash Isle.

Possible solution: keep only one (or a few) results in memory and write to HDF5 early. This could be done with a class which can be given numpy arrays one after the other and writes them to disk as necessary.

This would require:
- Changing the way measurements are saved. They would need to do it themselves instead of waiting for a call to `save`. This means the measurements need to know file name / HDF5 group at initialisation.
- Computing the number of configurations to measure on ahead of time to avoid resizing datasets and fragmenting files.

This might allow for some other improvements:
- Handle configurations in the same way i.e. collect several and save them together. Maybe difficult because configs are saved into separate datasets.
- Consolidate measurement output to reduce number of file accesses.

Do you have ideas / suggestions on this?

**Comment by evanberkowitz** [comment]
This is a great idea.  Some things to consider:

- Is it possible to put the i/o in a separate thread?
- Should a measurement buffer a few configurations worth of data and then do i/o?

The all-to-all propagator fits in memory?  What's the largest lattice for which we can get all-to-all with a reasonable memory footprint?

**Comment by evanberkowitz** [comment]
The space the all-to-all propagators consume is 

(2 species) * (Nx Nt)^2 * complex double = 32 (Nx Nt)^2 bytes.

If we say we want to max out at 8 GB = 2^33 bytes for the propagators, then Nx Nt = 2^14, which we could saturate pretty easily, surprisingly.  For example, C60 with 256 timeslices is almost that big.

**Comment by jl-wynen** [comment]
@nm439 knows more about when this breaks down. He observed it for some ribbons.
But of course, we need to use different algorithms for large lattices. But Lasse managed to get measurements on a few configs before the program crashed. So it seems worth optimising the current setup first.

- Separate thread: Maybe. That is tricky in Python because of the GIL plus it would interfere with the thread management in blaze / torch. Maybe h5py releases the GIL and all this would work almost out of the box, but I don't know.
- Buffer configs: absolutely. I was thinking about a configurable maximum number of results to buffer before output is triggered.

**Comment by evanberkowitz** [comment]
I could imagine maximum number of results or maximum memory footprint allowed for the measurement both being useful.
