### ISSUE TITLE
Make isle.Species iterable

### ISSUE THREAD

**Issue by evanberkowitz** [jl-wynen/isle#20]
It'd be nice to be able to say `for s in isle.Species` instead of `for s in (isle.Species.PARTICLE, isle.Species.HOLE)`, for example.

**Comment by jl-wynen** [comment]
Not sure this is possible. `isle.Species` is a pybind11 enum class. A quick search shows that we would need to use a custom metaclass to make the *class* object `isle.Species` iterable. pybind11 seems to support a mechanism for using custom metaclasses but it is not documented. I am unsure whether it is worth the effort to try and figure out how this works.

For reference, here is how it would work on *instances* of `Species`:
```.cpp
static Species SPECIES_VALUES[] = {Species::PARTICLE, Species::HOLE};

// ...

py::enum_<Species>(mod, "Species")
    .value("PARTICLE", Species::PARTICLE)
    .value("HOLE", Species::HOLE)
    .def("__iter__",
         [](const Species &){
             return py::make_iterator(SPECIES_VALUES,
                                      SPECIES_VALUES + sizeof(SPECIES_VALUES)/sizeof(Species::PARTICLE));
         });
```
You would then have to iterate over it via
```.py
for s in isle.Species(0):
    print(s)
```
which doesn't seem like a reasonable interface to me.

Alternatively, we could add a function along the lines of
```.cpp
py::enum_<Species>(mod, "Species")
    .value("PARTICLE", Species::PARTICLE)
    .value("HOLE", Species::HOLE)
    .def("iter",
         [](){
             return py::make_iterator(SPECIES_VALUES,
                                      SPECIES_VALUES + sizeof(SPECIES_VALUES)/sizeof(Species::PARTICLE));
         });
```
which would be used like
```.py
for s in isle.Species.iter():
    print(s)
```

**Comment by evanberkowitz** [comment]
[This closed pybind11 issue](https://github.com/pybind/pybind11/issues/253) was hoping to do the same; it's not clear if a pull request ever appeared.

**Comment by jl-wynen** [comment]
Added `Species.values()` iterator in d7acfe25fdfbfdc2701418dba6392f6744affc08. Not the nicest solution but doesn't require deep pybind11 hacking.

**Comment by evanberkowitz** [comment]
Better than nothing!
